### ISSUE TITLE
Not sure how to get this to work

### ISSUE THREAD

**Issue by imkane** [sethblack/pm2-gelf-pro#1]
First off, thanks for sharing this code!

I'm a rookie w/ Graylog, and have it running on a separate server. 

On this page (/system/inputs) I have a **GELF UDP** "Global input" running:

```
bind_address:` [full external IP address]
decompress_size_limit: 8388608
override_source: <empty>
port: 12201
recv_buffer_size: 262144
```

And I followed your instructions to setup pm2 -> graylog on the source server:

```
pm2 install pm2-gelf-pro

pm2 set pm2-gelf-pro:graylogHost [same ip as above]
pm2 set pm2-gelf-pro:graylogPort 12201
pm2 set pm2-gelf-pro:graylogFields '{"app": "myapp"}'
```

I've caused some errors in my Node app so that:
`/home/myuser/.pm2/logs/www-error.log`

Gets new data.

But the other (new) log files in this dir:
```
pm2-gelf-pro-error.log
pm2-gelf-pro-out.log
```

Are stuck at 0 bytes. And my Graylog server doesn't show any incoming data.

Any suggestions?

**Comment by sethblack** [comment]
Hiya!

Thank you very much. I appreciate that.

Hmm. Config seems good so far. And the `pm2-gelf-pro-error.log` and `pm2-gelf-pro-out.log` should be pretty quiet. What does `pm2 get` tell you?

**Comment by imkane** [comment]
Hey Seth!

Here ya go:

```
myuser@stage:~$ pm2 get
== pm2-gelf-pro ==
┌─────────────────┬─────────────────────┐
│ key             │ value               │
├─────────────────┼─────────────────────┤
│ graylogPort     │ 12201               │
│ graylogHost     │ [graylog-server-ip]     │
│ gelfAdapterName │ udp                 │
│ graylogFields   │ {"app": "myapp"} │
└─────────────────┴─────────────────────┘
== module-db-v2 ==
┌──────────────┬───────┐
│ key          │ value │
├──────────────┼───────┤
│ pm2-gelf-pro │ [obj… │
└──────────────┴───────┘
```

**Comment by sethblack** [comment]
Hmm. Ok. That looks good. From you stage server can you please run the following command and see if you get anything in Graylog? It uses netcat to send a single message over UDP. This should confirm there's nothing wrong with communication between the two boxes. Sorry for the goose chase, I'm just trying to narrow down the issue.

```
echo -e '{"version": "1.1","host":"sethserver.com","short_message":"Short message","full_message":"A really\n\nlong message","level":1}\0' | nc -w 1 -u [graylog-server-ip] 12201
```

**Comment by imkane** [comment]
Ok, I ran that command but I don't see anything in Graylog. However I'm not even sure where to look lol. It's a bit of a confusing interface.

At first I thought maybe this could be a firewall issue, but on the Graylog server (Ubuntu w/ ufw), port 9000 and 12201 are open.

**Comment by sethblack** [comment]
Yeah, it def takes a minute to get used to. I totally understand that. You'll want to click "Streams" in the top-left hand corner, then click on the "All Messages" stream. That should take you to a table and graph of all input data. The interface should be pretty sparse if there's no data coming in. Then, there should be a "Play" button in the top right hand corner, if you push that graylog will auto-refresh every 5 seconds.

Once that's running you'll want to double check that 12201/udp is open in ufw.

Send the message again from your stage server. If the "All Messages" stream is still quiet try sending the message from the Graylog server through localhost.

**Comment by imkane** [comment]
On page /streams/000000000000000000000001/search

> Nothing found in stream All messages

```
myuser@log:~$ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
22/tcp                     LIMIT       Anywhere
80/tcp                     ALLOW       Anywhere
443/tcp                    ALLOW       Anywhere
9000                       ALLOW       Anywhere
12201                      ALLOW       Anywhere
22/tcp (v6)                LIMIT       Anywhere (v6)
80/tcp (v6)                ALLOW       Anywhere (v6)
443/tcp (v6)               ALLOW       Anywhere (v6)
9000 (v6)                  ALLOW       Anywhere (v6)
12201 (v6)                 ALLOW       Anywhere (v6)

```

I then ran (on Graylog server):

`echo -e '{"version": "1.1","host":"sethserver.com","short_message":"Short message","full_message":"A really\n\nlong message","level":1}\0' | nc -w 1 -u localhost 12201`

But still nothing on Streams page.

Strange eh?

**Comment by imkane** [comment]
Looking at the logs, I think I have the wrong version of ElasticSearch!

I have 6.4.2, but it sounds like Graylog only supports 5.x?

I'll look into downgrading ...

**Comment by sethblack** [comment]
Sweet! Looks like you found it. I'm gonna go ahead and close this issue out for now. If, once you get everything up and running, you're still having issues with pm2-gelf-pro we can re-open this ticket.

Good luck!

**Comment by imkane** [comment]
I really appreciate your help, you rock!
